version: "3.3"
services:   
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=practicedocker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  practice_docker:
    image: practice_docker
    depends_on:
      - db
    ports:
      - 9001:3000
    volumes:
      - .:/app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'